= OPAL Helm chart
:toc: macro
:icons: font
:toclevels: 1

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Installation

OPAL Helm chart could be installed only with https://helm.sh/docs/[Helm 3].
The chart is published to public Helm repository, hosted on GitHub itself.

It's recommended to install OPAL into a dedicated namespace.

Add Helm repository

[source]
----
helm repo add opal https://authorizon.github.io/opal-helm-chart
helm repo update
----

Install the latest version

[source]
----
helm install --create-namespace -n opal-ns myopal opal/opal
----

Search for all available versions

[source]
----
helm search repo opal --versions
----

=== Deploy OPAL to your Kubernetes cluster

Install specific version (with default configuration):

[source]
----
helm install --create-namespace -n opal-ns --version x.x.x myopal opal/opal
----

Install specific version (with custom configuration provided as YAML):

[source]
----
helm install -f myvalues.yaml --create-namespace -n opal-ns --version x.x.x myopal opal/opal
----

myvalues.yaml must conform to the https://raw.githubusercontent.com/authorizon/opal-helm-chart/master/values.schema.json[json schema].

=== Verify installation

OPAL Client should populate embedded OPA instance with polices and data from configured Git repository.
To validate it - one could create port-forwarding to OPAL client Pod. Port 8181 is the embedded OPA agent.

[source]
----
kubectl port-forward -n opal-ns service/opal-client 8181:8181
----

Then, open http://localhost:8181/v1/data/ in your browser to check OPA data document state.

