{{- if .Values.client.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opal.clientServiceAccountName" . }}
  labels:
    {{- include "opal.clientLabels" . | nindent 4 }}
  {{- with .Values.client.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.client.serviceAccount.automount }}
{{- end }}
